services:
  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - db_net

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase_master
    hostname: hbase-master
    ports:
      - "16010:16010"
      - "9090:9090"
      - "8080:8080"
    extra_hosts:
      - "hbase-master:127.0.0.1"
    networks:
      - db_net

networks:
  db_net:
    driver: bridge
